export const IPC_CHANNELS = {
  local: {
    selectDirectory: 'local:select-directory',
    scan: 'local:scan',
    getScanSnapshot: 'local:get-scan-snapshot',
    scanEvent: 'local:scan-event',
    upload: 'local:upload',
    cancelUpload: 'local:cancel-upload',
    uploadEvent: 'local:upload-event',
  },
  libraryTools: {
    getSnapshot: 'library-tools:get-snapshot',
    getLauncherStatus: 'library-tools:get-launcher-status',
    tryCloseLauncher: 'library-tools:try-close-launcher',
    scan: 'library-tools:scan',
    cancelScan: 'library-tools:cancel-scan',
    recover: 'library-tools:recover',
    prepareMove: 'library-tools:prepare-move',
    startMove: 'library-tools:start-move',
    cancelMove: 'library-tools:cancel-move',
    event: 'library-tools:event',
  },
  auth: {
    getStatus: 'auth:get-status',
    login: 'auth:login',
    logout: 'auth:logout',
    statusEvent: 'auth:status-event',
  },
  cloud: {
    getSnapshot: 'cloud:get-snapshot',
    refresh: 'cloud:refresh',
    start: 'cloud:start',
    pause: 'cloud:pause',
    resume: 'cloud:resume',
    cancel: 'cloud:cancel',
    retry: 'cloud:retry',
    remove: 'cloud:remove',
    clearCompleted: 'cloud:clear-completed',
    event: 'cloud:event',
  },
  library: {
    getStatus: 'library:get-status',
    query: 'library:query',
    getDetails: 'library:get-details',
    refresh: 'library:refresh',
    changedEvent: 'library:changed-event',
  },
  settings: {
    get: 'settings:get',
    update: 'settings:update',
    changedEvent: 'settings:changed-event',
  },
  diagnostics: {
    getSnapshot: 'diagnostics:get-snapshot',
    export: 'diagnostics:export',
    revealLogs: 'diagnostics:reveal-logs',
  },
  updates: {
    getStatus: 'updates:get-status',
    check: 'updates:check',
    download: 'updates:download',
    install: 'updates:install',
    statusEvent: 'updates:status-event',
  },
  about: {
    getInfo: 'about:get-info',
  },
} as const
