class CountryData {
  final String code;
  final String name;
  final String flag;

  const CountryData({
    required this.code,
    required this.name,
    required this.flag,
  });
}

class CountryUtils {
  static const Map<String, CountryData> _countries = {
    'AD': CountryData(code: 'AD', name: 'Andorra', flag: '\u{1F1E6}\u{1F1E9}'),
    'AE': CountryData(code: 'AE', name: 'United Arab Emirates', flag: '\u{1F1E6}\u{1F1EA}'),
    'AF': CountryData(code: 'AF', name: 'Afghanistan', flag: '\u{1F1E6}\u{1F1EB}'),
    'AG': CountryData(code: 'AG', name: 'Antigua and Barbuda', flag: '\u{1F1E6}\u{1F1EC}'),
    'AI': CountryData(code: 'AI', name: 'Anguilla', flag: '\u{1F1E6}\u{1F1EE}'),
    'AL': CountryData(code: 'AL', name: 'Albania', flag: '\u{1F1E6}\u{1F1F1}'),
    'AM': CountryData(code: 'AM', name: 'Armenia', flag: '\u{1F1E6}\u{1F1F2}'),
    'AO': CountryData(code: 'AO', name: 'Angola', flag: '\u{1F1E6}\u{1F1F4}'),
    'AQ': CountryData(code: 'AQ', name: 'Antarctica', flag: '\u{1F1E6}\u{1F1F6}'),
    'AR': CountryData(code: 'AR', name: 'Argentina', flag: '\u{1F1E6}\u{1F1F7}'),
    'AS': CountryData(code: 'AS', name: 'American Samoa', flag: '\u{1F1E6}\u{1F1F8}'),
    'AT': CountryData(code: 'AT', name: 'Austria', flag: '\u{1F1E6}\u{1F1F9}'),
    'AU': CountryData(code: 'AU', name: 'Australia', flag: '\u{1F1E6}\u{1F1FA}'),
    'AW': CountryData(code: 'AW', name: 'Aruba', flag: '\u{1F1E6}\u{1F1FC}'),
    'AX': CountryData(code: 'AX', name: 'Aland Islands', flag: '\u{1F1E6}\u{1F1FD}'),
    'AZ': CountryData(code: 'AZ', name: 'Azerbaijan', flag: '\u{1F1E6}\u{1F1FF}'),
    'BA': CountryData(code: 'BA', name: 'Bosnia and Herzegovina', flag: '\u{1F1E7}\u{1F1E6}'),
    'BB': CountryData(code: 'BB', name: 'Barbados', flag: '\u{1F1E7}\u{1F1E7}'),
    'BD': CountryData(code: 'BD', name: 'Bangladesh', flag: '\u{1F1E7}\u{1F1E9}'),
    'BE': CountryData(code: 'BE', name: 'Belgium', flag: '\u{1F1E7}\u{1F1EA}'),
    'BF': CountryData(code: 'BF', name: 'Burkina Faso', flag: '\u{1F1E7}\u{1F1EB}'),
    'BG': CountryData(code: 'BG', name: 'Bulgaria', flag: '\u{1F1E7}\u{1F1EC}'),
    'BH': CountryData(code: 'BH', name: 'Bahrain', flag: '\u{1F1E7}\u{1F1ED}'),
    'BI': CountryData(code: 'BI', name: 'Burundi', flag: '\u{1F1E7}\u{1F1EE}'),
    'BJ': CountryData(code: 'BJ', name: 'Benin', flag: '\u{1F1E7}\u{1F1EF}'),
    'BL': CountryData(code: 'BL', name: 'Saint Barthelemy', flag: '\u{1F1E7}\u{1F1F1}'),
    'BM': CountryData(code: 'BM', name: 'Bermuda', flag: '\u{1F1E7}\u{1F1F2}'),
    'BN': CountryData(code: 'BN', name: 'Brunei', flag: '\u{1F1E7}\u{1F1F3}'),
    'BO': CountryData(code: 'BO', name: 'Bolivia', flag: '\u{1F1E7}\u{1F1F4}'),
    'BQ': CountryData(code: 'BQ', name: 'Caribbean Netherlands', flag: '\u{1F1E7}\u{1F1F6}'),
    'BR': CountryData(code: 'BR', name: 'Brazil', flag: '\u{1F1E7}\u{1F1F7}'),
    'BS': CountryData(code: 'BS', name: 'Bahamas', flag: '\u{1F1E7}\u{1F1F8}'),
    'BT': CountryData(code: 'BT', name: 'Bhutan', flag: '\u{1F1E7}\u{1F1F9}'),
    'BV': CountryData(code: 'BV', name: 'Bouvet Island', flag: '\u{1F1E7}\u{1F1FB}'),
    'BW': CountryData(code: 'BW', name: 'Botswana', flag: '\u{1F1E7}\u{1F1FC}'),
    'BY': CountryData(code: 'BY', name: 'Belarus', flag: '\u{1F1E7}\u{1F1FE}'),
    'BZ': CountryData(code: 'BZ', name: 'Belize', flag: '\u{1F1E7}\u{1F1FF}'),
    'CA': CountryData(code: 'CA', name: 'Canada', flag: '\u{1F1E8}\u{1F1E6}'),
    'CC': CountryData(code: 'CC', name: 'Cocos Islands', flag: '\u{1F1E8}\u{1F1E8}'),
    'CD': CountryData(code: 'CD', name: 'DR Congo', flag: '\u{1F1E8}\u{1F1E9}'),
    'CF': CountryData(code: 'CF', name: 'Central African Republic', flag: '\u{1F1E8}\u{1F1EB}'),
    'CG': CountryData(code: 'CG', name: 'Congo', flag: '\u{1F1E8}\u{1F1EC}'),
    'CH': CountryData(code: 'CH', name: 'Switzerland', flag: '\u{1F1E8}\u{1F1ED}'),
    'CI': CountryData(code: 'CI', name: 'Ivory Coast', flag: '\u{1F1E8}\u{1F1EE}'),
    'CK': CountryData(code: 'CK', name: 'Cook Islands', flag: '\u{1F1E8}\u{1F1F0}'),
    'CL': CountryData(code: 'CL', name: 'Chile', flag: '\u{1F1E8}\u{1F1F1}'),
    'CM': CountryData(code: 'CM', name: 'Cameroon', flag: '\u{1F1E8}\u{1F1F2}'),
    'CN': CountryData(code: 'CN', name: 'China', flag: '\u{1F1E8}\u{1F1F3}'),
    'CO': CountryData(code: 'CO', name: 'Colombia', flag: '\u{1F1E8}\u{1F1F4}'),
    'CR': CountryData(code: 'CR', name: 'Costa Rica', flag: '\u{1F1E8}\u{1F1F7}'),
    'CU': CountryData(code: 'CU', name: 'Cuba', flag: '\u{1F1E8}\u{1F1FA}'),
    'CV': CountryData(code: 'CV', name: 'Cape Verde', flag: '\u{1F1E8}\u{1F1FB}'),
    'CW': CountryData(code: 'CW', name: 'Curacao', flag: '\u{1F1E8}\u{1F1FC}'),
    'CX': CountryData(code: 'CX', name: 'Christmas Island', flag: '\u{1F1E8}\u{1F1FD}'),
    'CY': CountryData(code: 'CY', name: 'Cyprus', flag: '\u{1F1E8}\u{1F1FE}'),
    'CZ': CountryData(code: 'CZ', name: 'Czechia', flag: '\u{1F1E8}\u{1F1FF}'),
    'DE': CountryData(code: 'DE', name: 'Germany', flag: '\u{1F1E9}\u{1F1EA}'),
    'DJ': CountryData(code: 'DJ', name: 'Djibouti', flag: '\u{1F1E9}\u{1F1EF}'),
    'DK': CountryData(code: 'DK', name: 'Denmark', flag: '\u{1F1E9}\u{1F1F0}'),
    'DM': CountryData(code: 'DM', name: 'Dominica', flag: '\u{1F1E9}\u{1F1F2}'),
    'DO': CountryData(code: 'DO', name: 'Dominican Republic', flag: '\u{1F1E9}\u{1F1F4}'),
    'DZ': CountryData(code: 'DZ', name: 'Algeria', flag: '\u{1F1E9}\u{1F1FF}'),
    'EC': CountryData(code: 'EC', name: 'Ecuador', flag: '\u{1F1EA}\u{1F1E8}'),
    'EE': CountryData(code: 'EE', name: 'Estonia', flag: '\u{1F1EA}\u{1F1EA}'),
    'EG': CountryData(code: 'EG', name: 'Egypt', flag: '\u{1F1EA}\u{1F1EC}'),
    'EH': CountryData(code: 'EH', name: 'Western Sahara', flag: '\u{1F1EA}\u{1F1ED}'),
    'ER': CountryData(code: 'ER', name: 'Eritrea', flag: '\u{1F1EA}\u{1F1F7}'),
    'ES': CountryData(code: 'ES', name: 'Spain', flag: '\u{1F1EA}\u{1F1F8}'),
    'ET': CountryData(code: 'ET', name: 'Ethiopia', flag: '\u{1F1EA}\u{1F1F9}'),
    'FI': CountryData(code: 'FI', name: 'Finland', flag: '\u{1F1EB}\u{1F1EE}'),
    'FJ': CountryData(code: 'FJ', name: 'Fiji', flag: '\u{1F1EB}\u{1F1EF}'),
    'FK': CountryData(code: 'FK', name: 'Falkland Islands', flag: '\u{1F1EB}\u{1F1F0}'),
    'FM': CountryData(code: 'FM', name: 'Micronesia', flag: '\u{1F1EB}\u{1F1F2}'),
    'FO': CountryData(code: 'FO', name: 'Faroe Islands', flag: '\u{1F1EB}\u{1F1F4}'),
    'FR': CountryData(code: 'FR', name: 'France', flag: '\u{1F1EB}\u{1F1F7}'),
    'GA': CountryData(code: 'GA', name: 'Gabon', flag: '\u{1F1EC}\u{1F1E6}'),
    'GB': CountryData(code: 'GB', name: 'United Kingdom', flag: '\u{1F1EC}\u{1F1E7}'),
    'GD': CountryData(code: 'GD', name: 'Grenada', flag: '\u{1F1EC}\u{1F1E9}'),
    'GE': CountryData(code: 'GE', name: 'Georgia', flag: '\u{1F1EC}\u{1F1EA}'),
    'GF': CountryData(code: 'GF', name: 'French Guiana', flag: '\u{1F1EC}\u{1F1EB}'),
    'GG': CountryData(code: 'GG', name: 'Guernsey', flag: '\u{1F1EC}\u{1F1EC}'),
    'GH': CountryData(code: 'GH', name: 'Ghana', flag: '\u{1F1EC}\u{1F1ED}'),
    'GI': CountryData(code: 'GI', name: 'Gibraltar', flag: '\u{1F1EC}\u{1F1EE}'),
    'GL': CountryData(code: 'GL', name: 'Greenland', flag: '\u{1F1EC}\u{1F1F1}'),
    'GM': CountryData(code: 'GM', name: 'Gambia', flag: '\u{1F1EC}\u{1F1F2}'),
    'GN': CountryData(code: 'GN', name: 'Guinea', flag: '\u{1F1EC}\u{1F1F3}'),
    'GP': CountryData(code: 'GP', name: 'Guadeloupe', flag: '\u{1F1EC}\u{1F1F5}'),
    'GQ': CountryData(code: 'GQ', name: 'Equatorial Guinea', flag: '\u{1F1EC}\u{1F1F6}'),
    'GR': CountryData(code: 'GR', name: 'Greece', flag: '\u{1F1EC}\u{1F1F7}'),
    'GS': CountryData(code: 'GS', name: 'South Georgia', flag: '\u{1F1EC}\u{1F1F8}'),
    'GT': CountryData(code: 'GT', name: 'Guatemala', flag: '\u{1F1EC}\u{1F1F9}'),
    'GU': CountryData(code: 'GU', name: 'Guam', flag: '\u{1F1EC}\u{1F1FA}'),
    'GW': CountryData(code: 'GW', name: 'Guinea-Bissau', flag: '\u{1F1EC}\u{1F1FC}'),
    'GY': CountryData(code: 'GY', name: 'Guyana', flag: '\u{1F1EC}\u{1F1FE}'),
    'HK': CountryData(code: 'HK', name: 'Hong Kong', flag: '\u{1F1ED}\u{1F1F0}'),
    'HM': CountryData(code: 'HM', name: 'Heard and McDonald Islands', flag: '\u{1F1ED}\u{1F1F2}'),
    'HN': CountryData(code: 'HN', name: 'Honduras', flag: '\u{1F1ED}\u{1F1F3}'),
    'HR': CountryData(code: 'HR', name: 'Croatia', flag: '\u{1F1ED}\u{1F1F7}'),
    'HT': CountryData(code: 'HT', name: 'Haiti', flag: '\u{1F1ED}\u{1F1F9}'),
    'HU': CountryData(code: 'HU', name: 'Hungary', flag: '\u{1F1ED}\u{1F1FA}'),
    'ID': CountryData(code: 'ID', name: 'Indonesia', flag: '\u{1F1EE}\u{1F1E9}'),
    'IE': CountryData(code: 'IE', name: 'Ireland', flag: '\u{1F1EE}\u{1F1EA}'),
    'IL': CountryData(code: 'IL', name: 'Israel', flag: '\u{1F1EE}\u{1F1F1}'),
    'IM': CountryData(code: 'IM', name: 'Isle of Man', flag: '\u{1F1EE}\u{1F1F2}'),
    'IN': CountryData(code: 'IN', name: 'India', flag: '\u{1F1EE}\u{1F1F3}'),
    'IO': CountryData(code: 'IO', name: 'British Indian Ocean Territory', flag: '\u{1F1EE}\u{1F1F4}'),
    'IQ': CountryData(code: 'IQ', name: 'Iraq', flag: '\u{1F1EE}\u{1F1F6}'),
    'IR': CountryData(code: 'IR', name: 'Iran', flag: '\u{1F1EE}\u{1F1F7}'),
    'IS': CountryData(code: 'IS', name: 'Iceland', flag: '\u{1F1EE}\u{1F1F8}'),
    'IT': CountryData(code: 'IT', name: 'Italy', flag: '\u{1F1EE}\u{1F1F9}'),
    'JE': CountryData(code: 'JE', name: 'Jersey', flag: '\u{1F1EF}\u{1F1EA}'),
    'JM': CountryData(code: 'JM', name: 'Jamaica', flag: '\u{1F1EF}\u{1F1F2}'),
    'JO': CountryData(code: 'JO', name: 'Jordan', flag: '\u{1F1EF}\u{1F1F4}'),
    'JP': CountryData(code: 'JP', name: 'Japan', flag: '\u{1F1EF}\u{1F1F5}'),
    'KE': CountryData(code: 'KE', name: 'Kenya', flag: '\u{1F1F0}\u{1F1EA}'),
    'KG': CountryData(code: 'KG', name: 'Kyrgyzstan', flag: '\u{1F1F0}\u{1F1EC}'),
    'KH': CountryData(code: 'KH', name: 'Cambodia', flag: '\u{1F1F0}\u{1F1ED}'),
    'KI': CountryData(code: 'KI', name: 'Kiribati', flag: '\u{1F1F0}\u{1F1EE}'),
    'KM': CountryData(code: 'KM', name: 'Comoros', flag: '\u{1F1F0}\u{1F1F2}'),
    'KN': CountryData(code: 'KN', name: 'Saint Kitts and Nevis', flag: '\u{1F1F0}\u{1F1F3}'),
    'KP': CountryData(code: 'KP', name: 'North Korea', flag: '\u{1F1F0}\u{1F1F5}'),
    'KR': CountryData(code: 'KR', name: 'South Korea', flag: '\u{1F1F0}\u{1F1F7}'),
    'KW': CountryData(code: 'KW', name: 'Kuwait', flag: '\u{1F1F0}\u{1F1FC}'),
    'KY': CountryData(code: 'KY', name: 'Cayman Islands', flag: '\u{1F1F0}\u{1F1FE}'),
    'KZ': CountryData(code: 'KZ', name: 'Kazakhstan', flag: '\u{1F1F0}\u{1F1FF}'),
    'LA': CountryData(code: 'LA', name: 'Laos', flag: '\u{1F1F1}\u{1F1E6}'),
    'LB': CountryData(code: 'LB', name: 'Lebanon', flag: '\u{1F1F1}\u{1F1E7}'),
    'LC': CountryData(code: 'LC', name: 'Saint Lucia', flag: '\u{1F1F1}\u{1F1E8}'),
    'LI': CountryData(code: 'LI', name: 'Liechtenstein', flag: '\u{1F1F1}\u{1F1EE}'),
    'LK': CountryData(code: 'LK', name: 'Sri Lanka', flag: '\u{1F1F1}\u{1F1F0}'),
    'LR': CountryData(code: 'LR', name: 'Liberia', flag: '\u{1F1F1}\u{1F1F7}'),
    'LS': CountryData(code: 'LS', name: 'Lesotho', flag: '\u{1F1F1}\u{1F1F8}'),
    'LT': CountryData(code: 'LT', name: 'Lithuania', flag: '\u{1F1F1}\u{1F1F9}'),
    'LU': CountryData(code: 'LU', name: 'Luxembourg', flag: '\u{1F1F1}\u{1F1FA}'),
    'LV': CountryData(code: 'LV', name: 'Latvia', flag: '\u{1F1F1}\u{1F1FB}'),
    'LY': CountryData(code: 'LY', name: 'Libya', flag: '\u{1F1F1}\u{1F1FE}'),
    'MA': CountryData(code: 'MA', name: 'Morocco', flag: '\u{1F1F2}\u{1F1E6}'),
    'MC': CountryData(code: 'MC', name: 'Monaco', flag: '\u{1F1F2}\u{1F1E8}'),
    'MD': CountryData(code: 'MD', name: 'Moldova', flag: '\u{1F1F2}\u{1F1E9}'),
    'ME': CountryData(code: 'ME', name: 'Montenegro', flag: '\u{1F1F2}\u{1F1EA}'),
    'MF': CountryData(code: 'MF', name: 'Saint Martin', flag: '\u{1F1F2}\u{1F1EB}'),
    'MG': CountryData(code: 'MG', name: 'Madagascar', flag: '\u{1F1F2}\u{1F1EC}'),
    'MH': CountryData(code: 'MH', name: 'Marshall Islands', flag: '\u{1F1F2}\u{1F1ED}'),
    'MK': CountryData(code: 'MK', name: 'North Macedonia', flag: '\u{1F1F2}\u{1F1F0}'),
    'ML': CountryData(code: 'ML', name: 'Mali', flag: '\u{1F1F2}\u{1F1F1}'),
    'MM': CountryData(code: 'MM', name: 'Myanmar', flag: '\u{1F1F2}\u{1F1F2}'),
    'MN': CountryData(code: 'MN', name: 'Mongolia', flag: '\u{1F1F2}\u{1F1F3}'),
    'MO': CountryData(code: 'MO', name: 'Macau', flag: '\u{1F1F2}\u{1F1F4}'),
    'MP': CountryData(code: 'MP', name: 'Northern Mariana Islands', flag: '\u{1F1F2}\u{1F1F5}'),
    'MQ': CountryData(code: 'MQ', name: 'Martinique', flag: '\u{1F1F2}\u{1F1F6}'),
    'MR': CountryData(code: 'MR', name: 'Mauritania', flag: '\u{1F1F2}\u{1F1F7}'),
    'MS': CountryData(code: 'MS', name: 'Montserrat', flag: '\u{1F1F2}\u{1F1F8}'),
    'MT': CountryData(code: 'MT', name: 'Malta', flag: '\u{1F1F2}\u{1F1F9}'),
    'MU': CountryData(code: 'MU', name: 'Mauritius', flag: '\u{1F1F2}\u{1F1FA}'),
    'MV': CountryData(code: 'MV', name: 'Maldives', flag: '\u{1F1F2}\u{1F1FB}'),
    'MW': CountryData(code: 'MW', name: 'Malawi', flag: '\u{1F1F2}\u{1F1FC}'),
    'MX': CountryData(code: 'MX', name: 'Mexico', flag: '\u{1F1F2}\u{1F1FD}'),
    'MY': CountryData(code: 'MY', name: 'Malaysia', flag: '\u{1F1F2}\u{1F1FE}'),
    'MZ': CountryData(code: 'MZ', name: 'Mozambique', flag: '\u{1F1F2}\u{1F1FF}'),
    'NA': CountryData(code: 'NA', name: 'Namibia', flag: '\u{1F1F3}\u{1F1E6}'),
    'NC': CountryData(code: 'NC', name: 'New Caledonia', flag: '\u{1F1F3}\u{1F1E8}'),
    'NE': CountryData(code: 'NE', name: 'Niger', flag: '\u{1F1F3}\u{1F1EA}'),
    'NF': CountryData(code: 'NF', name: 'Norfolk Island', flag: '\u{1F1F3}\u{1F1EB}'),
    'NG': CountryData(code: 'NG', name: 'Nigeria', flag: '\u{1F1F3}\u{1F1EC}'),
    'NI': CountryData(code: 'NI', name: 'Nicaragua', flag: '\u{1F1F3}\u{1F1EE}'),
    'NL': CountryData(code: 'NL', name: 'Netherlands', flag: '\u{1F1F3}\u{1F1F1}'),
    'NO': CountryData(code: 'NO', name: 'Norway', flag: '\u{1F1F3}\u{1F1F4}'),
    'NP': CountryData(code: 'NP', name: 'Nepal', flag: '\u{1F1F3}\u{1F1F5}'),
    'NR': CountryData(code: 'NR', name: 'Nauru', flag: '\u{1F1F3}\u{1F1F7}'),
    'NU': CountryData(code: 'NU', name: 'Niue', flag: '\u{1F1F3}\u{1F1FA}'),
    'NZ': CountryData(code: 'NZ', name: 'New Zealand', flag: '\u{1F1F3}\u{1F1FF}'),
    'OM': CountryData(code: 'OM', name: 'Oman', flag: '\u{1F1F4}\u{1F1F2}'),
    'PA': CountryData(code: 'PA', name: 'Panama', flag: '\u{1F1F5}\u{1F1E6}'),
    'PE': CountryData(code: 'PE', name: 'Peru', flag: '\u{1F1F5}\u{1F1EA}'),
    'PF': CountryData(code: 'PF', name: 'French Polynesia', flag: '\u{1F1F5}\u{1F1EB}'),
    'PG': CountryData(code: 'PG', name: 'Papua New Guinea', flag: '\u{1F1F5}\u{1F1EC}'),
    'PH': CountryData(code: 'PH', name: 'Philippines', flag: '\u{1F1F5}\u{1F1ED}'),
    'PK': CountryData(code: 'PK', name: 'Pakistan', flag: '\u{1F1F5}\u{1F1F0}'),
    'PL': CountryData(code: 'PL', name: 'Poland', flag: '\u{1F1F5}\u{1F1F1}'),
    'PM': CountryData(code: 'PM', name: 'Saint Pierre and Miquelon', flag: '\u{1F1F5}\u{1F1F2}'),
    'PN': CountryData(code: 'PN', name: 'Pitcairn Islands', flag: '\u{1F1F5}\u{1F1F3}'),
    'PR': CountryData(code: 'PR', name: 'Puerto Rico', flag: '\u{1F1F5}\u{1F1F7}'),
    'PS': CountryData(code: 'PS', name: 'Palestine', flag: '\u{1F1F5}\u{1F1F8}'),
    'PT': CountryData(code: 'PT', name: 'Portugal', flag: '\u{1F1F5}\u{1F1F9}'),
    'PW': CountryData(code: 'PW', name: 'Palau', flag: '\u{1F1F5}\u{1F1FC}'),
    'PY': CountryData(code: 'PY', name: 'Paraguay', flag: '\u{1F1F5}\u{1F1FE}'),
    'QA': CountryData(code: 'QA', name: 'Qatar', flag: '\u{1F1F6}\u{1F1E6}'),
    'RE': CountryData(code: 'RE', name: 'Reunion', flag: '\u{1F1F7}\u{1F1EA}'),
    'RO': CountryData(code: 'RO', name: 'Romania', flag: '\u{1F1F7}\u{1F1F4}'),
    'RS': CountryData(code: 'RS', name: 'Serbia', flag: '\u{1F1F7}\u{1F1F8}'),
    'RU': CountryData(code: 'RU', name: 'Russia', flag: '\u{1F1F7}\u{1F1FA}'),
    'RW': CountryData(code: 'RW', name: 'Rwanda', flag: '\u{1F1F7}\u{1F1FC}'),
    'SA': CountryData(code: 'SA', name: 'Saudi Arabia', flag: '\u{1F1F8}\u{1F1E6}'),
    'SB': CountryData(code: 'SB', name: 'Solomon Islands', flag: '\u{1F1F8}\u{1F1E7}'),
    'SC': CountryData(code: 'SC', name: 'Seychelles', flag: '\u{1F1F8}\u{1F1E8}'),
    'SD': CountryData(code: 'SD', name: 'Sudan', flag: '\u{1F1F8}\u{1F1E9}'),
    'SE': CountryData(code: 'SE', name: 'Sweden', flag: '\u{1F1F8}\u{1F1EA}'),
    'SG': CountryData(code: 'SG', name: 'Singapore', flag: '\u{1F1F8}\u{1F1EC}'),
    'SH': CountryData(code: 'SH', name: 'Saint Helena', flag: '\u{1F1F8}\u{1F1ED}'),
    'SI': CountryData(code: 'SI', name: 'Slovenia', flag: '\u{1F1F8}\u{1F1EE}'),
    'SJ': CountryData(code: 'SJ', name: 'Svalbard and Jan Mayen', flag: '\u{1F1F8}\u{1F1EF}'),
    'SK': CountryData(code: 'SK', name: 'Slovakia', flag: '\u{1F1F8}\u{1F1F0}'),
    'SL': CountryData(code: 'SL', name: 'Sierra Leone', flag: '\u{1F1F8}\u{1F1F1}'),
    'SM': CountryData(code: 'SM', name: 'San Marino', flag: '\u{1F1F8}\u{1F1F2}'),
    'SN': CountryData(code: 'SN', name: 'Senegal', flag: '\u{1F1F8}\u{1F1F3}'),
    'SO': CountryData(code: 'SO', name: 'Somalia', flag: '\u{1F1F8}\u{1F1F4}'),
    'SR': CountryData(code: 'SR', name: 'Suriname', flag: '\u{1F1F8}\u{1F1F7}'),
    'SS': CountryData(code: 'SS', name: 'South Sudan', flag: '\u{1F1F8}\u{1F1F8}'),
    'ST': CountryData(code: 'ST', name: 'Sao Tome and Principe', flag: '\u{1F1F8}\u{1F1F9}'),
    'SV': CountryData(code: 'SV', name: 'El Salvador', flag: '\u{1F1F8}\u{1F1FB}'),
    'SX': CountryData(code: 'SX', name: 'Sint Maarten', flag: '\u{1F1F8}\u{1F1FD}'),
    'SY': CountryData(code: 'SY', name: 'Syria', flag: '\u{1F1F8}\u{1F1FE}'),
    'SZ': CountryData(code: 'SZ', name: 'Eswatini', flag: '\u{1F1F8}\u{1F1FF}'),
    'TC': CountryData(code: 'TC', name: 'Turks and Caicos Islands', flag: '\u{1F1F9}\u{1F1E8}'),
    'TD': CountryData(code: 'TD', name: 'Chad', flag: '\u{1F1F9}\u{1F1E9}'),
    'TF': CountryData(code: 'TF', name: 'French Southern Territories', flag: '\u{1F1F9}\u{1F1EB}'),
    'TG': CountryData(code: 'TG', name: 'Togo', flag: '\u{1F1F9}\u{1F1EC}'),
    'TH': CountryData(code: 'TH', name: 'Thailand', flag: '\u{1F1F9}\u{1F1ED}'),
    'TJ': CountryData(code: 'TJ', name: 'Tajikistan', flag: '\u{1F1F9}\u{1F1EF}'),
    'TK': CountryData(code: 'TK', name: 'Tokelau', flag: '\u{1F1F9}\u{1F1F0}'),
    'TL': CountryData(code: 'TL', name: 'Timor-Leste', flag: '\u{1F1F9}\u{1F1F1}'),
    'TM': CountryData(code: 'TM', name: 'Turkmenistan', flag: '\u{1F1F9}\u{1F1F2}'),
    'TN': CountryData(code: 'TN', name: 'Tunisia', flag: '\u{1F1F9}\u{1F1F3}'),
    'TO': CountryData(code: 'TO', name: 'Tonga', flag: '\u{1F1F9}\u{1F1F4}'),
    'TR': CountryData(code: 'TR', name: 'Turkey', flag: '\u{1F1F9}\u{1F1F7}'),
    'TT': CountryData(code: 'TT', name: 'Trinidad and Tobago', flag: '\u{1F1F9}\u{1F1F9}'),
    'TV': CountryData(code: 'TV', name: 'Tuvalu', flag: '\u{1F1F9}\u{1F1FB}'),
    'TW': CountryData(code: 'TW', name: 'Taiwan', flag: '\u{1F1F9}\u{1F1FC}'),
    'TZ': CountryData(code: 'TZ', name: 'Tanzania', flag: '\u{1F1F9}\u{1F1FF}'),
    'UA': CountryData(code: 'UA', name: 'Ukraine', flag: '\u{1F1FA}\u{1F1E6}'),
    'UG': CountryData(code: 'UG', name: 'Uganda', flag: '\u{1F1FA}\u{1F1EC}'),
    'UM': CountryData(code: 'UM', name: 'U.S. Minor Outlying Islands', flag: '\u{1F1FA}\u{1F1F2}'),
    'US': CountryData(code: 'US', name: 'United States', flag: '\u{1F1FA}\u{1F1F8}'),
    'UY': CountryData(code: 'UY', name: 'Uruguay', flag: '\u{1F1FA}\u{1F1FE}'),
    'UZ': CountryData(code: 'UZ', name: 'Uzbekistan', flag: '\u{1F1FA}\u{1F1FF}'),
    'VA': CountryData(code: 'VA', name: 'Vatican City', flag: '\u{1F1FB}\u{1F1E6}'),
    'VC': CountryData(code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '\u{1F1FB}\u{1F1E8}'),
    'VE': CountryData(code: 'VE', name: 'Venezuela', flag: '\u{1F1FB}\u{1F1EA}'),
    'VG': CountryData(code: 'VG', name: 'British Virgin Islands', flag: '\u{1F1FB}\u{1F1EC}'),
    'VI': CountryData(code: 'VI', name: 'U.S. Virgin Islands', flag: '\u{1F1FB}\u{1F1EE}'),
    'VN': CountryData(code: 'VN', name: 'Vietnam', flag: '\u{1F1FB}\u{1F1F3}'),
    'VU': CountryData(code: 'VU', name: 'Vanuatu', flag: '\u{1F1FB}\u{1F1FA}'),
    'WF': CountryData(code: 'WF', name: 'Wallis and Futuna', flag: '\u{1F1FC}\u{1F1EB}'),
    'WS': CountryData(code: 'WS', name: 'Samoa', flag: '\u{1F1FC}\u{1F1F8}'),
    'XK': CountryData(code: 'XK', name: 'Kosovo', flag: '\u{1F1FD}\u{1F1F0}'),
    'YE': CountryData(code: 'YE', name: 'Yemen', flag: '\u{1F1FE}\u{1F1EA}'),
    'YT': CountryData(code: 'YT', name: 'Mayotte', flag: '\u{1F1FE}\u{1F1F9}'),
    'ZA': CountryData(code: 'ZA', name: 'South Africa', flag: '\u{1F1FF}\u{1F1E6}'),
    'ZM': CountryData(code: 'ZM', name: 'Zambia', flag: '\u{1F1FF}\u{1F1F2}'),
    'ZW': CountryData(code: 'ZW', name: 'Zimbabwe', flag: '\u{1F1FF}\u{1F1FC}'),
  };

  static CountryData? getCountry(String code) {
    return _countries[code.toUpperCase()];
  }

  static String getCountryName(String code) {
    return _countries[code.toUpperCase()]?.name ?? code;
  }

  static String getCountryFlag(String code) {
    return _countries[code.toUpperCase()]?.flag ?? '';
  }

  static List<CountryData> getCountriesForCodes(List<String> codes) {
    return codes
        .map((code) => _countries[code.toUpperCase()])
        .whereType<CountryData>()
        .toList();
  }

  static List<CountryData> searchCountries(List<String> availableCodes, String query) {
    final lowerQuery = query.toLowerCase();
    return availableCodes
        .map((code) => _countries[code.toUpperCase()])
        .whereType<CountryData>()
        .where((country) =>
            country.name.toLowerCase().contains(lowerQuery) ||
            country.code.toLowerCase().contains(lowerQuery))
        .toList();
  }
}
